<a href="https://colab.research.google.com/github/techasit239/Final-Project---DADS6003/blob/main/Stylometric_Features_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
import numpy as np
import IPython
from IPython.display import display
import gdown

In [ ]:
train_file_id = "1NZIkHAGvoqcMOFAj_ONpi-0GRc6ZNEwN"
test_file_id = "1NJcC72cNH0PbR4hRq1OpZvUF5OHzU1ye"
train_url = f"https://drive.google.com/uc?id={train_file_id}"
test_url = f"https://drive.google.com/uc?id={test_file_id}"

In [ ]:
output_train = "train.csv"
output_test = "test.csv"
gdown.download(train_url, output_train, quiet=False)
gdown.download(test_url, output_test, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1NZIkHAGvoqcMOFAj_ONpi-0GRc6ZNEwN
To: /content/train.csv
100%|██████████| 189k/189k [00:00<00:00, 47.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NJcC72cNH0PbR4hRq1OpZvUF5OHzU1ye
To: /content/test.csv
100%|██████████| 48.8k/48.8k [00:00<00:00, 57.7MB/s]

'test.csv'

In [ ]:
df = pd.read_csv(output_train)
df.head()

,Subject,Body,Label
0,An Exciting Opportunity to Engage in a Persona...,"Dear David,\n\nI hope this email finds you in ...",Legitimate
1,New Exciting Relationship Opportunity! From Lo...,"Dear Julia,\n\nWe hope this email finds you we...",Phishing
2,Important Account Notification â€“ Action Requ...,"Dear Toni, \n\nI hope this message finds you w...",Legitimate
3,Exclusive Financial Opportunity Awaits - Inves...,"Dear Chelsea,\n\nI hope this communication fin...",Legitimate
4,Introducing Groundbreaking Health Enhancement ...,"Dear Christine, \n\nI hope this email finds yo...",Legitimate

In [ ]:
# Punctuation Features (2 features)
def punctuation_features(row):
  s = str(row["Subject"]) + " " + str(row["Body"])
  s_count = len(s)
  target_punc = ['.', ',', ':', '-', '"', '(', ')', '/', '\\' ]

  total_punc_count = 0
  variety_count = 0

  if (s_count==0):
    return {
        "punctuation_frequency" : 0.0,
        "punctuation_variety" : 0
    }
  for punc in target_punc:
    punc_count = s.count(punc)
    total_punc_count += punc_count
    if (punc_count>0):
      variety_count += 1
  return {
      "punctuation_frequenc": total_punc_count/s_count,
      "punctutation_variety" : variety_count
  }

feature_result = df.apply(punctuation_features, axis=1, result_type="expand")
df_punc = pd.concat([df, feature_result], axis=1)
display(df_punc.head())

output_fname = "train_processed.csv"
df_punc.to_csv(output_fname, index = False)

,Subject,Body,Label,punctuation_frequenc,punctutation_variety
0,An Exciting Opportunity to Engage in a Persona...,"Dear David,\n\nI hope this email finds you in ...",Legitimate,0.014046,2.0
1,New Exciting Relationship Opportunity! From Lo...,"Dear Julia,\n\nWe hope this email finds you we...",Phishing,0.077703,6.0
2,Important Account Notification â€“ Action Requ...,"Dear Toni, \n\nI hope this message finds you w...",Legitimate,0.014674,4.0
3,Exclusive Financial Opportunity Awaits - Inves...,"Dear Chelsea,\n\nI hope this communication fin...",Legitimate,0.015721,3.0
4,Introducing Groundbreaking Health Enhancement ...,"Dear Christine, \n\nI hope this email finds yo...",Legitimate,0.018078,3.0

In [ ]:
!pip install textstat
import textstat

Collecting textstat
  Downloading textstat-0.7.11-py3-none-any.whl.metadata (15 kB)
Collecting pyphen (from textstat)
  Downloading pyphen-0.17.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from textstat) (3.9.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from textstat) (75.2.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->textstat) (8.3.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->textstat) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->textstat) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->textstat) (4.67.1)
Downloading textstat-0.7.11-py3-none-any.whl (176 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.4/176.4 kB 4.4 MB/s eta 0:00:00
Downloading pyphen-0.17.2-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 23.5 MB/s eta 0:00:00
Installing collected packages: pyphen, textstat
Successfully installed pyphen-0.17.2 textstat-0.7.11

In [ ]:
# Readability Scores Features (5 features)
## 1. Flesch Reading Ease
## 2. SMOG Index
## 3. Dale--Chall Readability Score
## 4. Coleman--Liau Index (CLI)
## 5. Gunning Fog Index (GFI)

def readability_score_features(row):
  s = str(row["Subject"]) + " " + str(row["Body"])
  fre = textstat.flesch_reading_ease(s)
  smog = textstat.smog_index(s)
  dale_chall = textstat.dale_chall_readability_score_v2(s)
  cli = textstat.coleman_liau_index(s)
  return {
      "fleasch_reading_ease" : fre,
      "smog_index": smog,
      "dale_chall_readability_score": dale_chall,
      "coleman_Liau_index": cli,
      "gunning_fog_index": textstat.gunning_fog(s)
  }

feature_result = df.apply(readability_score_features, axis=1, result_type="expand")
feature_result.head()

df_features = pd.concat([df_punc, feature_result], axis=1)
display(df_features.head())

df_features.to_csv("train_processed.csv", index=False)

,Subject,Body,Label,punctuation_frequenc,punctutation_variety,fleasch_reading_ease,smog_index,dale_chall_readability_score,coleman_Liau_index,gunning_fog_index
0,An Exciting Opportunity to Engage in a Persona...,"Dear David,\n\nI hope this email finds you in ...",Legitimate,0.014046,2.0,40.498027,14.150737,9.143110,12.500288,14.742811
1,New Exciting Relationship Opportunity! From Lo...,"Dear Julia,\n\nWe hope this email finds you we...",Phishing,0.077703,6.0,57.074571,11.368140,8.923270,10.703492,10.500317
2,Important Account Notification â€“ Action Requ...,"Dear Toni, \n\nI hope this message finds you w...",Legitimate,0.014674,4.0,38.653038,14.554593,9.639150,12.569072,15.110052
3,Exclusive Financial Opportunity Awaits - Inves...,"Dear Chelsea,\n\nI hope this communication fin...",Legitimate,0.015721,3.0,32.416929,15.043977,10.344036,14.976786,15.529524
4,Introducing Groundbreaking Health Enhancement ...,"Dear Christine, \n\nI hope this email finds yo...",Legitimate,0.018078,3.0,37.708664,15.207997,9.738018,13.601869,16.649514